
spring:
  application:
    name: admin-server

server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info


